version: '3.2'
services:
    postgres:
        image: postgres
        container_name: click_game_postgres
        environment:
          POSTGRES_USER: devpostgres
          POSTGRES_PASSWORD: click
          POSTGRES_DB: click_game_dev
        volumes:
          - postgres-data-click-game/var/lib/postgresql/data
        restart: always
        ports:
          - 5432:5432

    adminer:
        image: adminer
        container_name: hypert_adminer
        restart: always
        ports:
          - 8080:8080
volumes:
    postgres-data-click-game:
      driver: local
